// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMhw3n-MuDxdtGPO5s1jg_1nn4HNqdjLo',
    appId: '1:160207124436:web:430f3ebf3435354f240841',
    messagingSenderId: '160207124436',
    projectId: 'dht11-firebase-92fe9',
    authDomain: 'dht11-firebase-92fe9.firebaseapp.com',
    databaseURL: 'https://dht11-firebase-92fe9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'dht11-firebase-92fe9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7F3-_PYON5bG1nycXdyM0DgcAVb4A8h4',
    appId: '1:160207124436:android:aa4ea682cfe0e35a240841',
    messagingSenderId: '160207124436',
    projectId: 'dht11-firebase-92fe9',
    databaseURL: 'https://dht11-firebase-92fe9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'dht11-firebase-92fe9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNvTGwxfKS4Yg6NB57GwA0m_aFTxPiTVw',
    appId: '1:160207124436:ios:4143f8f47a70411a240841',
    messagingSenderId: '160207124436',
    projectId: 'dht11-firebase-92fe9',
    databaseURL: 'https://dht11-firebase-92fe9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'dht11-firebase-92fe9.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNvTGwxfKS4Yg6NB57GwA0m_aFTxPiTVw',
    appId: '1:160207124436:ios:4143f8f47a70411a240841',
    messagingSenderId: '160207124436',
    projectId: 'dht11-firebase-92fe9',
    databaseURL: 'https://dht11-firebase-92fe9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'dht11-firebase-92fe9.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMhw3n-MuDxdtGPO5s1jg_1nn4HNqdjLo',
    appId: '1:160207124436:web:174d41e79cfd7bac240841',
    messagingSenderId: '160207124436',
    projectId: 'dht11-firebase-92fe9',
    authDomain: 'dht11-firebase-92fe9.firebaseapp.com',
    databaseURL: 'https://dht11-firebase-92fe9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'dht11-firebase-92fe9.firebasestorage.app',
  );

}