// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP9JRjWTes6W5U8vaqijWR4zyKiN7ZQzo',
    appId: '1:736469950577:web:031acfc06f4c5d59b6fbd0',
    messagingSenderId: '736469950577',
    projectId: 'smart-home-demo-20c25',
    authDomain: 'smart-home-demo-20c25.firebaseapp.com',
    databaseURL: 'https://smart-home-demo-20c25-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-home-demo-20c25.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDRThi3MpfcA2cZbDhhYFknS8eHIvV558',
    appId: '1:736469950577:android:e2061577a9876c54b6fbd0',
    messagingSenderId: '736469950577',
    projectId: 'smart-home-demo-20c25',
    databaseURL: 'https://smart-home-demo-20c25-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-home-demo-20c25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdyAnQ5Qfy6_b-3_inguY56mxMywjP3hQ',
    appId: '1:736469950577:ios:9e3cd5f08c20728ab6fbd0',
    messagingSenderId: '736469950577',
    projectId: 'smart-home-demo-20c25',
    databaseURL: 'https://smart-home-demo-20c25-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-home-demo-20c25.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdyAnQ5Qfy6_b-3_inguY56mxMywjP3hQ',
    appId: '1:736469950577:ios:9e3cd5f08c20728ab6fbd0',
    messagingSenderId: '736469950577',
    projectId: 'smart-home-demo-20c25',
    databaseURL: 'https://smart-home-demo-20c25-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-home-demo-20c25.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAP9JRjWTes6W5U8vaqijWR4zyKiN7ZQzo',
    appId: '1:736469950577:web:2ac6c6af44e529a8b6fbd0',
    messagingSenderId: '736469950577',
    projectId: 'smart-home-demo-20c25',
    authDomain: 'smart-home-demo-20c25.firebaseapp.com',
    databaseURL: 'https://smart-home-demo-20c25-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-home-demo-20c25.firebasestorage.app',
  );

}